name: Apply Supabase migrations

on:
  push:
    branches: [ "main" ]
    paths:
      - 'supabase/migrations/**'
  workflow_dispatch: {}

jobs:
  apply-migrations:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Supabase CLI
        uses: supabase/setup-cli@v1

      - name: Link Supabase project
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase link --project-ref "${{ secrets.SUPABASE_PROJECT_REF }}"

      - name: Apply migrations to remote database
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase db push

      - name: Print applied migrations
        run: |
          echo "Migrations applied successfully."
